apiVersion: v2
name: comments-system
description: A Helm chart for deploying the Comments System on OpenShift
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - comments
  - microservices
  - openshift
maintainers:
  - name: Comments System Team
    email: team@comments-system.com
