{{- if .Values.secrets.postgres }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.postgres.name }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.postgres.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
